name: netcdf-scm
channels:
  - default
  - conda-forge
dependencies:
  # tidy up all this later and move relevant bits into setup.py
  # for now this is just a list of things I think we'll need
  # - iris
  # - netcdftime
  # - pandas
  - pip
  - pip:
    - versioneer
    - pytest
    # - "git+https://github.com/thedataincubator/expectexception.git@master"
    # - nbval
    # - "git+https://github.com/openclimatedata/pymagicc.git@master"
    # - matplotlib
    # - nbresuse
    # - progressbar2
    # - tables
    # - jupyter_contrib_nbextensions
    # - notebook
    # can change this once the weird failure with jupyter installation
    # goes away, see https://github.com/pypa/pip/issues/5839
    # - ipython<7
    # - prompt-toolkit==1.0.15
